### ISSUE TITLE
Document how to add input to an actor

### ISSUE THREAD

**Issue by rokcarl** [apify/apify-client-python#121]
I'm trying to find out how to run an actor and specify the input for it. E.g., the [LinkedIn Company URL](https://apify.com/anchor/linkedin-company-url-finder) needs something like `{"queries": "Tesla\nmicrosoft.com"}`

The [API docs are clear](https://docs.apify.com/api/v2/#/reference/actors/run-collection) that whatever data is passed to the `POST` request will be interpreted as input to the actor.

However, I can't find a proper alternative in the Python docs, e.g. in the [Usage concepts](https://docs.apify.com/api/client/python/docs/usage-concepts). There's dataset's `push_items()`, but I don't think that's it. Is there an equivalent?

**Comment by fnesveda** [comment]
Good point. The API Client docs aren't really good right now, and they don't have many examples. We've been focusing mostly on the SDK docs these days, but we should give some love to the client docs too.

Anyway, to add input to an actor, you can just pass an argument to the [`ActorClient.call()`](https://docs.apify.com/api/client/python/reference/class/ActorClient#call) method:
```python
run = apify_client.actor("anchor/linkedin-company-url").call(run_input={"queries": "Tesla\nmicrosoft.com"})
```

**Comment by rokcarl** [comment]
Thanks, that works.
