### ISSUE TITLE
Creating Actor from Template missing package.json

### ISSUE THREAD

**Issue by daviddcarmon** [apify/apify-client-python#127]
Running `apify create my-first-actor --template python-start`

`Error: ENOENT: no such file or directory, open \my-first-actor\package.json`

You are able manually add package.json and start script to run actor.

Issue Type: LOW

**Comment by fnesveda** [comment]
Hi, you need to update your Apify CLI to a newer version, the support for creating and running Python Actors was added only in February, in [version 0.14.1](https://github.com/apify/apify-cli/releases).

You can check which version of the CLI you have installed by running `apify --version`.

**Comment by daviddcarmon** [comment]
apify-cli/0.7.4 win32-x64 node-v18.15.0

running a --update to the cli

I get Requirement already satisfied

I guess I needed to removed the apify-cli and apify then reinstalled 
apify-cli/0.16.1 win32-x64 node-v18.15.0
