### ISSUE TITLE
Get max_no_of_posts using insta_posts_scraper

### ISSUE THREAD

**Issue by hamza1424** [apify/apify-client-python#128]
We can't retrieve all posts for a user, it only returns posts from the first page:
Here is our script:
```

from apify_client import ApifyClient


from apify_client import ApifyClient
apify_client = ApifyClient('token')


actor_call = apify_client.actor('apify/instagram-post-scraper').call(run_input={'username' : ['username'], "limit": 100}, )
### get dataset and posts 
dataset_items = apify_client.dataset(actor_call['defaultDatasetId']).list_items().items

```
Is there any way work around to fix this?

**Comment by fnesveda** [comment]
Hi, I see you've also opened the same issue directly on the Instagram Post Scraper, which is the correct place for this problem. I will close this issue here, as it's not directly related to the Python API client.
