### ISSUE TITLE
Not possible to add maxItems parameter.

### ISSUE THREAD

**Issue by sadigaxund** [apify/apify-client-python#146]
Hello,
Judging from source code, I believe, it is not possible to specify **maxItems** parameter like this:

> https://api.apify.com/v2/acts/actor-name/runs?token=YOUR_TOKEN&maxItems=10

Something like this:
`actor.start(run_input={some input},  memory_mbytes=32768,  build='latest',  timeout_secs=100,  max_items=100)
`

Please correct me if I'm wrong, and if so what's the way of accomplishing this?

**Comment by fnesveda** [comment]
Hi, good catch! The support for specifying the `maxItems` parameter was missing from the Python API client, I've added it in #148, a new version with that change merged will be released in the next few days.
