### ISSUE TITLE
Data in webhook response does not contain the custom payload

### ISSUE THREAD

**Issue by wired87** [apify/apify-client-python#189]
I try to call an actor which crawl data from a website. After successfully endeing it should trigger a webhook event - whill all work great BUT im unable to receive the payload template with my custom data. i also found nothin in the docs. 
thats my code (if i write the key's in camleCase it triggers an error whic just say the key with underscore (i also try set the paylload_template key with underscore but it also doesnt work):
https://gist.github.com/wired87/7c1c9ae5a81473d82e14ddf033b2967a

and thats alltime the response (userId is not the userId that i have paste into my custom payload function:
https://gist.github.com/wired87/5eca18c1dcba387735afd76a34d05968

**Comment by janbuchar** [comment]
Hello, from looking at your code, the `payloadTemplate` should be in snake_case, i.e. `payload_template`. It's just a hunch, but it looks like what you're receiving is the default payload, not the one you're trying to configure.
