### ISSUE TITLE
1.7.0 is a breaking change

### ISSUE THREAD

**Issue by jakerobers** [apify/apify-client-python#240]
We discovered a regression in our app when moving to 1.7.0:

```
task_last_run = await task_last_run_client.get() or {}
                          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'get'
```

The changelog mentioned that the last_run method was adjusted to be asynchronous, but is listed as a fix. I would consider this a breaking change since application patches are required to migrate to this version.

**Comment by vdusek** [comment]
I'm sorry, this is clearly our mistake, and things like this should not happen. We made some changes on the API side, and as a result, we should be able to revert this breaking change in version 1.7.1.
