### ISSUE TITLE
Cannot use Apify Python Client at Coegil platform

### ISSUE THREAD

**Issue by mtrunkat** [apify/apify-client-python#79]
From email conversation:

> We are using Coegil platform to run apify-client library and getting this issue.
>
> Pip install passed fine, installing all dependencies.
>
> from apify_client import ApifyClient
>
> ModuleNotFoundError: No module named 'apify_client'

**Comment by fnesveda** [comment]
This is most probably not a bug with the Python Client, but rather with the way the user is installing the package at Coegil, which is a very closed off data science platform. I think there's nothing we can do about this.
